<?php

namespace InscripcionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * interesadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class interesadosRepository extends EntityRepository
{
    public function ListaInteresados(){
        $sql = "SELECT * FROM dbo.tbl_interesados  ORDER BY id_inte DESC;";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();
        $datos = $stmt->fetchAll(); //para array multidimensional
        return $datos;
    }

}
